# Data import and pre-processing

This notebook contains code for data import from the database and data pre-processing (cleaning, manipulation etc.).

## Data import

In this section, tables are imported from the database and saved as a pandas dataframe.

##### TGE

In [422]:
# connect to database and fetch rows

import psycopg2

conn = psycopg2.connect(
    host="192.168.30.11",
    port=5432,
    dbname="db_data_hoarder",
    user="urszula_wolanowska",
    password="UrsWol1@",
)
cur = conn.cursor()


cur.execute("SELECT delivery_date, time, fixing_ii_price FROM tge_rdnquarters;") # quarters
rows_tge_rndquarters = cur.fetchall()


cur.execute("SELECT delivery_date, time, fixing_ii_price FROM tge_rdnhours;")
rows_tge_rdnhours = cur.fetchall()


cur.execute("SELECT delivery_date, time, fixing_ii_price FROM tge_rdn;")
rows_tge_rdn = cur.fetchall()



conn.close()

In [423]:
# create a data frame object using fetched rows

import pandas as pd

tge_rdnquarters = pd.DataFrame(rows_tge_rndquarters, columns = ["Date", "Time", "Price_ii"])
tge_rdnhours = pd.DataFrame(rows_tge_rdnhours, columns = ["Date", "Time", "Price_ii"])
tge_rdn = pd.DataFrame(rows_tge_rdn, columns = ["Date", "Time", "Price_ii"])


# note: tge_rdn to jest starsza tabela, ze starszymi danymi. tge_rdnhours zostało utworzone kiedy zaczęły pojawiać się 15minutówki

##### Weather

In [424]:
# connect to database and fetch rows

import psycopg2

conn = psycopg2.connect(
    host="192.168.30.11",
    port=5432,
    dbname="db_data_hoarder",
    user="urszula_wolanowska",
    password="UrsWol1@",
)
cur = conn.cursor()


cur.execute("SELECT miasto, czas_prognozy, temperatura, wilgotnosc, opady, naslonecznienie, predkosc_wiatru   FROM weather_forecast;") # quarters
weather_forecast = cur.fetchall()


cur.execute("SELECT czas, temperatura, wilgotnosc, opady, naslonecznienie, predkosc_wiatru FROM weather_weatherdata;")
weather = cur.fetchall()


conn.close()

In [425]:
# create a data frame object using fetched rows

import pandas as pd

weather_forecast = pd.DataFrame(weather_forecast, columns = ["Miasto", "Czas", "Temperatura", "Wilgotność", "Opady", "Nasłonecznienie", "Prędkość_wiatru"])
weather = pd.DataFrame(weather, columns = ["Czas", "Temperatura", "Wilgotność", "Opady", "Nasłonecznienie", "Prędkość_wiatru"])

##### KSE

In [426]:
# connect to database and fetch rows

import psycopg2

conn = psycopg2.connect(
    host="192.168.30.11",
    port=5432,
    dbname="db_data_hoarder",
    user="urszula_wolanowska",
    password="UrsWol1@",
)
cur = conn.cursor()


cur.execute("SELECT dtime, period, load_fcst, load_actual, business_date FROM pse_kseload ;") # quarters
rows_kse_load = cur.fetchall()
cols_kse_load = [desc[0] for desc in cur.description]


conn.close()

In [427]:
# create a dataframe object 

import pandas as pd

kse_load = pd.DataFrame(rows_kse_load, columns = cols_kse_load)

#####

## Data cleaning

In this section, data is cleaned to change data type and remove missing values.

##### TGE

In [428]:
# change date and time to string

tge_rdnquarters["Date"] = tge_rdnquarters["Date"].astype("str")
tge_rdnquarters["Time"] = tge_rdnquarters["Time"].astype("str")

tge_rdn["Date"] = tge_rdn["Date"].astype("str")
tge_rdn["Time"] = tge_rdn["Time"].astype("str")

tge_rdnhours["Date"] = tge_rdnhours["Date"].astype("str")
tge_rdnhours["Time"] = tge_rdnhours["Time"].astype("str")

# combine date and time columns to create datetime column

tge_rdnquarters["Datetime"] = tge_rdnquarters["Date"] + " " + tge_rdnquarters["Time"]

tge_rdn["Datetime"] = tge_rdn["Date"] + " " + tge_rdn["Time"]

tge_rdnhours["Datetime"] = tge_rdnhours["Date"] + " " + tge_rdnhours["Time"]

# change data type to date

tge_rdnquarters["Datetime"] = pd.to_datetime(tge_rdnquarters["Datetime"])

tge_rdn["Datetime"] = pd.to_datetime(tge_rdn["Datetime"])

tge_rdnhours["Datetime"] = pd.to_datetime(tge_rdnhours["Datetime"])

In [429]:
# remove missing values

tge_rdnquarters_filtered = tge_rdnquarters[pd.notnull(tge_rdnquarters["Price_ii"])]
# tge_rdn = tge_rdn[pd.notnull(tge_rdn["Price_i"])]
# tge_rdnhours = tge_rdnhours[pd.notna(tge_rdnhours["Price_i"])]

In [430]:
# remove repeated rows

repeated_dates = tge_rdnquarters_filtered["Datetime"].value_counts()[tge_rdnquarters_filtered["Datetime"].value_counts() >=2].index

tge_rdnquarters_filtered = tge_rdnquarters_filtered[~tge_rdnquarters_filtered["Datetime"].isin(repeated_dates)]

##### Weather

In [431]:
# change to datetype

weather["Czas"] = pd.to_datetime(weather["Czas"], utc = True).dt.tz_convert("Europe/Warsaw").dt.tz_localize(None)
weather_forecast["Czas"] = pd.to_datetime(weather_forecast["Czas"], utc = True).dt.tz_convert("Europe/Warsaw").dt.tz_localize(None)

In [432]:
# remove rows with duplicate (repeated measurement at same time for same city)

weather_forecast_filtered = weather_forecast[~weather_forecast[["Miasto", "Czas"]].duplicated(keep = False)]

In [433]:
# remove rows with Zielona Góra (too few measurements)

weather_forecast_filtered = weather_forecast_filtered[~(weather_forecast_filtered["Miasto"] == "Zielona Góra")]

In [ ]:
# remove rows without full day (less than 24 measurements for the same day for each city)

In [436]:
weather_forecast_filtered = weather_forecast_filtered.drop(["Wilgotność", "Opady"], axis = 1)

##### KSE

In [437]:
# change datype to date

kse_load["dtime"] = pd.to_datetime(kse_load["dtime"], utc = True).dt.tz_convert("Europe/Warsaw").dt.tz_localize(None)

In [438]:
kse_load["business_date"] = pd.to_datetime(kse_load["business_date"])
kse_load["load_actual"] = kse_load["load_actual"].astype(float)
kse_load["load_fcst"] = kse_load["load_fcst"].astype(float)

In [439]:
# adjust datetime by 15min 

kse_load["dtime"] = kse_load["dtime"] - pd.Timedelta(minutes=15)

## Data Manipulation

##### TGE

In this part, datasets for 1 hour are combined together (tge_rdn and tge_rdnhours)

In [61]:
# combine 1 hour dataset

# tge_rdn["Date"] = pd.to_datetime(tge_rdn["Date"])

# tge_rdn_filtered = tge_rdn[tge_rdn["Date"] < "2025-09-01"] # filter tge_rdn

# tge_rdnhours_combined = pd.concat([tge_rdn_filtered, tge_rdnhours])

In [62]:
# save hours combined to database

# from sqlalchemy import create_engine

# engine = create_engine("postgresql+psycopg2://urszula_wolanowska:UrsWol1@192.168.30.11:5432/db_data_hoarder")

# tge_rdnhours_combined.to_sql()

In this part, dataset on 15 min (tge_rdnquarters) is manipulated to create pivot columns for previous day and day ahead. Prices from the original dataset are looked up for previous day and current day.

In [440]:
# creaty empty dataset 

tge_rdnquarters_transformed = []
tge_rdnquarters_transformed = pd.DataFrame(tge_rdnquarters_transformed)


# add previous day and day ahead

tge_rdnquarters_transformed["Previous_day_datetime"] = tge_rdnquarters_filtered["Datetime"] # adds previous day
tge_rdnquarters_transformed["Day_ahead_datetime"] = tge_rdnquarters_transformed["Previous_day_datetime"] + pd.Timedelta(days=1) # adds day ahead


# filter data 

tge_rdnquarters_transformed = tge_rdnquarters_transformed[tge_rdnquarters_transformed["Day_ahead_datetime"].isin(tge_rdnquarters_filtered["Datetime"])]

In [441]:
# Look up prices for previous day and day ahead

tge_rdnquarters_transformed_merged = pd.merge(tge_rdnquarters_transformed, tge_rdnquarters_filtered,
                                    left_on = "Previous_day_datetime", right_on = "Datetime", 
                                    how = "left") # prices for previous day

tge_rdnquarters_transformed_merged = pd.merge(tge_rdnquarters_transformed_merged, tge_rdnquarters_filtered, 
                                    left_on = "Day_ahead_datetime", right_on = "Datetime", 
                                    how = "left") # prices for day ahead

In [442]:
# Clean the merged data (drop columns and rename)

tge_rdnquarters_transformed_merged = tge_rdnquarters_transformed_merged.drop(columns = ["Datetime_x", "Datetime_y"]) # drop unnecessary columns

tge_rdnquarters_transformed_merged = tge_rdnquarters_transformed_merged.rename(columns = {"Price_i_x": "Price_i_previous_day", "Price_ii_x": "Price_ii_previous_day", "Date_x": "Date_previous_day", "Time_x": "Time_previous_day",
                                                                                          "Price_i_y": "Price_i_day_ahead", "Price_ii_y": "Price_ii_day_ahead", "Date_y": "Date_day_ahead", "Time_y": "Time_day_ahead"})

##### Weather

Average weather measurements across the whole country are taken for each hour.

In [443]:
# average weather measuremenents for each hour

weather_mean = weather.groupby(["Czas"]).mean()
weather_forecast_mean = weather_forecast_filtered.groupby(["Czas", "Miasto"]).mean().reset_index()

In [445]:
# pivot the weather measurements

weather_forecast_pivot =  weather_forecast_mean.pivot(columns = ["Miasto"], values = ["Temperatura", "Nasłonecznienie", "Prędkość_wiatru"], index = ["Czas"])

weather_forecast_pivot.columns = [
    f"{variable}_miasto_{city}"
    for variable, city in weather_forecast_pivot.columns
]

weather_forecast_pivot = weather_forecast_pivot.reset_index()

##### KSE

In [33]:
# adjust datetime

## Save data

Data on TGE RDN prices, weather and KSE is combined together and saved.

In [446]:
# create a column with date and hour only for tge rdn quarters

tge_rdnquarters_transformed_merged["Previous_day_date_hour"] = tge_rdnquarters_transformed_merged["Previous_day_datetime"].dt.floor("h")
tge_rdnquarters_transformed_merged["Day_ahead_date_hour"] = tge_rdnquarters_transformed_merged["Day_ahead_datetime"].dt.floor("h")


# note: hourly column is required to look up weather and weather forecast measurements

In [447]:
# merge TGE RDN 15min with weather measurements

# tge_rdnquarters_weather = pd.merge(tge_rdnquarters_transformed_merged, weather_mean, 
                                #    left_on = "Previous_day_date_hour", right_on = "Czas", 
                                #    how = "left")

tge_rdnquarters_weather_forecast = pd.merge(tge_rdnquarters_transformed_merged, weather_forecast_pivot,
                                           left_on = "Day_ahead_date_hour", right_on = "Czas",
                                           how = "left")



# rename the columns

# tge_rdnquarters_weather_forecast = tge_rdnquarters_weather_forecast.rename(columns = {"Temperatura_x": "Temperatura_previous_day", 
#                                                                                       "Wilgotność_x":"Wilgotność_previous_day",
#                                                                                       "Opady_x": "Opady_previous_day",
#                                                                                       "Nasłonecznienie_x": "Nasłonecznienie_previous_day",
#                                                                                       "Prędkość_wiatru_x": "Prędkość_wiatru_previous_day",
#                                                                                       "Temperatura_y": "Temperatura_forecast", 
#                                                                                       "Wilgotność_y":"Wilgotność_forecast",
#                                                                                       "Opady_y": "Opady_forecast",
#                                                                                       "Nasłonecznienie_y": "Nasłonecznienie_forecast",
#                                                                                       "Prędkość_wiatru_y": "Prędkość_wiatru_forecast"})

In [448]:
tge_rdnquarters_transformed_merged["Date_day_ahead"].value_counts()

Date_day_ahead
2025-11-20    96
2025-11-21    96
2025-11-22    96
2025-12-13    96
2025-12-16    96
              ..
2026-10-16    96
2026-10-17    96
2026-10-18    96
2026-10-19    96
2026-10-20    96
Name: count, Length: 339, dtype: int64

In [ ]:
# remove rows with missing weather

# tge_rdnquarters_weather_forecast = tge_rdnquarters_weather_forecast[pd.notna(tge_rdnquarters_weather_forecast["Temperatura_forecast"])]

# addtionally remove rows for day ahead = 2026-03-31 (has some weather measurements missing and some present, so gets removed anyway)

# tge_rdnquarters_weather_forecast = tge_rdnquarters_weather_forecast[~(tge_rdnquarters_weather_forecast["Date_day_ahead"] == "2026-03-31")]

In [449]:
# remove rows with missing values

tge_rdnquarters_weather_forecast = tge_rdnquarters_weather_forecast[~tge_rdnquarters_weather_forecast.isna().any(axis=1)]

In [450]:
# remove dates that have not had 96 measurements

date_index = tge_rdnquarters_weather_forecast["Date_day_ahead"].value_counts()[tge_rdnquarters_weather_forecast["Date_day_ahead"].value_counts() < 96].index

tge_rdnquarters_weather_forecast = tge_rdnquarters_weather_forecast[~tge_rdnquarters_weather_forecast["Date_day_ahead"].isin(date_index)]

In [456]:
len(tge_rdnquarters_weather_forecast_kse)/96

296.0

In [452]:
# merge with kse_load

tge_rdnquarters_weather_forecast_kse = pd.merge(tge_rdnquarters_weather_forecast, kse_load, 
                                                left_on = "Day_ahead_datetime", right_on = "dtime", how = "left")

In [453]:
# remove rows 

tge_rdnquarters_weather_forecast_kse = tge_rdnquarters_weather_forecast_kse[pd.notna(tge_rdnquarters_weather_forecast_kse["load_fcst"])] # check if there are any missing values for load forecast

In [455]:
# remove rows thet have not had full day measurements 

date_index = tge_rdnquarters_weather_forecast_kse["Date_day_ahead"].value_counts()[tge_rdnquarters_weather_forecast_kse["Date_day_ahead"].value_counts() < 96].index

tge_rdnquarters_weather_forecast_kse = tge_rdnquarters_weather_forecast_kse[~tge_rdnquarters_weather_forecast_kse["Date_day_ahead"].isin(date_index)]

In [293]:
# merge TGE RDN hours and weather

# pd.merge(tge_rdnhours_combined, weather,
        #  left_on =["Date_previous_day", "Hour_previous_day"], right_on = ["Dzień", "Godzina"], 
        #  how = "left")

# tge_rdn_quarters_weather = tge_rdn_quarters_weather[pd.notna[tge_rdn_quarters_weather["Previous_day_datetime"]]]

In [457]:
# Add day of week

tge_rdnquarters_weather_forecast_kse["Day_of_week"] = tge_rdnquarters_weather_forecast_kse["Day_ahead_datetime"].dt.day_name()

In [458]:
# sort values before saving 

tge_rdnquarters_weather_forecast_kse = tge_rdnquarters_weather_forecast_kse.sort_values(["Previous_day_datetime"])

In [459]:
# drop columns 

tge_rdnquarters_weather_forecast_kse = tge_rdnquarters_weather_forecast_kse.drop(["Previous_day_datetime", "Day_ahead_datetime", "Date_previous_day", "Time_previous_day", "Time_day_ahead", "Previous_day_date_hour", "Day_ahead_date_hour", "Czas",
                                                                                  "dtime", "period", "business_date"], axis = 1)

In [460]:
# Save the final datasets

import sqlite3

con = sqlite3.connect("db_data_hoarder_ula.db") # establish connection to database

# tge_rdnquarters_transformed_merged.to_sql("tge_rdnquarters", con, if_exists="replace", index = False)
# tge_rdnhours.to_sql("tge_rdnhours", con, if_exists = "replace", index = False)
# weather_forecast.to_sql("weather_forecast_processed", con, if_exists="replace", index = False)
# weather.to_sql("weather_processed", con, if_exists="replace", index = False)



tge_rdnquarters_weather_forecast_kse.to_sql("tge_rdnquarters_weather_forecast_kse", con, if_exists="replace", index = False)

con.close()

In [461]:
len(tge_rdnquarters_weather_forecast_kse)/96

296.0

In [421]:
tge_rdnquarters_weather_forecast_kse[tge_rdnquarters_weather_forecast_kse.isna().any(axis=1)]

,Price_ii_previous_day,Date_day_ahead,Price_ii_day_ahead,Temperatura_miasto_Białystok,Temperatura_miasto_Gdańsk,Temperatura_miasto_Gorzów Wielkopolski,Temperatura_miasto_Katowice,Temperatura_miasto_Kielce,Temperatura_miasto_Kraków,Temperatura_miasto_Lublin,...,Prędkość_wiatru_miasto_Puławy,Prędkość_wiatru_miasto_Rzeszów,Prędkość_wiatru_miasto_Szczecin,Prędkość_wiatru_miasto_Toruń,Prędkość_wiatru_miasto_Warszawa,Prędkość_wiatru_miasto_Wrocław,Prędkość_wiatru_miasto_Łódź,load_fcst,load_actual,Day_of_week
9025,427.75,2026-03-11,437.13,6.98,7.61,9.57,9.76,8.12,10.01,8.33,...,4.02,6.31,1.47,2.68,2.78,3.32,4.02,17750.0,NaN,Wednesday
9026,419.48,2026-03-11,430.44,6.98,7.61,9.57,9.76,8.12,10.01,8.33,...,4.02,6.31,1.47,2.68,2.78,3.32,4.02,17400.0,NaN,Wednesday
9027,395.98,2026-03-11,428.57,6.22,7.25,9.10,9.07,8.44,9.41,7.59,...,4.21,6.02,1.42,2.61,3.11,3.21,4.30,17050.0,NaN,Wednesday
9028,390.20,2026-03-11,440.49,6.22,7.25,9.10,9.07,8.44,9.41,7.59,...,4.21,6.02,1.42,2.61,3.11,3.21,4.30,16850.0,NaN,Wednesday
14496,613.65,2026-05-22,636.32,20.22,16.12,18.20,18.59,20.49,18.64,17.37,...,5.69,5.56,3.59,6.14,4.18,4.37,5.97,20650.0,NaN,Friday
14497,583.96,2026-05-22,628.98,20.22,16.12,18.20,18.59,20.49,18.64,17.37,...,5.69,5.56,3.59,6.14,4.18,4.37,5.97,20350.0,NaN,Friday
14498,556.82,2026-05-22,599.43,20.22,16.12,18.20,18.59,20.49,18.64,17.37,...,5.69,5.56,3.59,6.14,4.18,4.37,5.97,19900.0,NaN,Friday
14499,524.35,2026-05-22,583.50,19.77,16.53,18.44,19.53,18.35,18.22,17.38,...,5.09,5.72,3.50,5.09,4.65,4.80,6.52,19450.0,NaN,Friday
14500,553.89,2026-05-22,638.14,19.77,16.53,18.44,19.53,18.35,18.22,17.38,...,5.09,5.72,3.50,5.09,4.65,4.80,6.52,18900.0,NaN,Friday
14501,530.86,2026-05-22,583.81,19.77,16.53,18.44,19.53,18.35,18.22,17.38,...,5.09,5.72,3.50,5.09,4.65,4.80,6.52,18600.0,NaN,Friday
14502,507.34,2026-05-22,572.26,19.77,16.53,18.44,19.53,18.35,18.22,17.38,...,5.09,5.72,3.50,5.09,4.65,4.80,6.52,18350.0,NaN,Friday
14503,493.41,2026-05-22,559.69,19.20,16.37,19.45,18.14,16.99,17.23,17.21,...,4.38,6.19,3.32,4.99,4.41,5.94,6.46,17900.0,NaN,Friday
14504,503.56,2026-05-22,571.40,19.20,16.37,19.45,18.14,16.99,17.23,17.21,...,4.38,6.19,3.32,4.99,4.41,5.94,6.46,17500.0,NaN,Friday
14505,493.90,2026-05-22,569.28,19.20,16.37,19.45,18.14,16.99,17.23,17.21,...,4.38,6.19,3.32,4.99,4.41,5.94,6.46,17150.0,NaN,Friday
14506,494.67,2026-05-22,564.65,19.20,16.37,19.45,18.14,16.99,17.23,17.21,...,4.38,6.19,3.32,4.99,4.41,5.94,6.46,16800.0,NaN,Friday
14507,498.79,2026-05-22,565.85,17.50,15.24,19.23,17.61,16.03,16.44,16.82,...,3.36,5.03,2.69,4.02,4.18,5.27,5.30,16450.0,NaN,Friday
14508,484.71,2026-05-22,562.99,17.50,15.24,19.23,17.61,16.03,16.44,16.82,...,3.36,5.03,2.69,4.02,4.18,5.27,5.30,16100.0,NaN,Friday
27080,375.86,2026-10-10,298.13,12.06,10.35,11.70,10.71,10.94,11.94,11.46,...,5.44,2.79,5.68,4.38,5.11,3.21,4.55,17500.0,NaN,Saturday
27081,356.34,2026-10-10,243.85,12.06,10.35,11.70,10.71,10.94,11.94,11.46,...,5.44,2.79,5.68,4.38,5.11,3.21,4.55,17100.0,NaN,Saturday
27082,355.15,2026-10-10,248.84,12.06,10.35,11.70,10.71,10.94,11.94,11.46,...,5.44,2.79,5.68,4.38,5.11,3.21,4.55,16750.0,NaN,Saturday
27083,295.89,2026-10-10,264.18,11.52,10.35,11.96,9.85,10.00,10.65,10.87,...,4.67,2.68,5.73,4.19,4.81,3.96,4.12,16400.0,NaN,Saturday
27084,345.67,2026-10-10,236.34,11.52,10.35,11.96,9.85,10.00,10.65,10.87,...,4.67,2.68,5.73,4.19,4.81,3.96,4.12,16150.0,NaN,Saturday

In [419]:
tge_rdnquarters_weather_forecast_kse.dropna()

,Price_ii_previous_day,Date_day_ahead,Price_ii_day_ahead,Temperatura_miasto_Białystok,Temperatura_miasto_Gdańsk,Temperatura_miasto_Gorzów Wielkopolski,Temperatura_miasto_Katowice,Temperatura_miasto_Kielce,Temperatura_miasto_Kraków,Temperatura_miasto_Lublin,...,Prędkość_wiatru_miasto_Puławy,Prędkość_wiatru_miasto_Rzeszów,Prędkość_wiatru_miasto_Szczecin,Prędkość_wiatru_miasto_Toruń,Prędkość_wiatru_miasto_Warszawa,Prędkość_wiatru_miasto_Wrocław,Prędkość_wiatru_miasto_Łódź,load_fcst,load_actual,Day_of_week
0,408.84,2025-11-20,454.50,-0.26,3.33,2.60,1.96,0.26,1.21,0.00,...,2.59,3.44,3.87,2.70,2.87,4.30,3.35,19350.0,19839.168,Thursday
1,371.08,2025-11-20,454.49,-0.26,3.33,2.60,1.96,0.26,1.21,0.00,...,2.59,3.44,3.87,2.70,2.87,4.30,3.35,18950.0,19549.285,Thursday
2,367.07,2025-11-20,454.47,-0.26,3.33,2.60,1.96,0.26,1.21,0.00,...,2.59,3.44,3.87,2.70,2.87,4.30,3.35,18700.0,19254.785,Thursday
3,362.92,2025-11-20,454.50,-0.26,3.33,2.60,1.96,0.26,1.21,0.00,...,2.59,3.44,3.87,2.70,2.87,4.30,3.35,18350.0,18798.035,Thursday
4,404.43,2025-11-20,455.85,-0.14,3.62,2.51,1.73,0.26,1.12,0.19,...,2.43,4.27,4.12,2.78,2.70,4.31,3.72,18050.0,18430.477,Thursday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28026,618.63,2026-10-19,745.45,7.80,9.82,13.78,11.23,8.73,14.10,8.66,...,3.40,3.36,4.33,3.47,2.72,2.95,2.87,22850.0,22847.400,Monday
28027,647.18,2026-10-19,754.48,7.26,9.68,11.05,9.24,8.64,10.40,8.86,...,3.68,3.43,3.78,3.48,2.76,3.01,3.27,22850.0,22743.092,Monday
28028,474.99,2026-10-19,882.37,7.26,9.68,11.05,9.24,8.64,10.40,8.86,...,3.68,3.43,3.78,3.48,2.76,3.01,3.27,22750.0,22528.470,Monday
28029,498.92,2026-10-19,781.93,7.26,9.68,11.05,9.24,8.64,10.40,8.86,...,3.68,3.43,3.78,3.48,2.76,3.01,3.27,22550.0,22430.637,Monday
28030,486.29,2026-10-19,600.15,7.26,9.68,11.05,9.24,8.64,10.40,8.86,...,3.68,3.43,3.78,3.48,2.76,3.01,3.27,22350.0,22332.473,Monday

In [ ]:
# lol